shop/ecomapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('products/<product_slug>/', views.product_view, name='product_detail'),
    path('category/<category_slug>/', views.category_view, name='category_detail'),
    path('cart/', views.cart_view, name='cart'),
    path('add_to_cart/', views.add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart/', views.remove_from_cart_view, name='remove_from_cart'),
    path('change_item_qty/', views.change_item_qty, name='change_item_qty'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('order/', views.order_create_view, name='create_order')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/ecomapp/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save
from django.utils.text import slugify
from transliterate import translit
from django.urls import reverse
from decimal import Decimal


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)

class Discount(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    image = models.ImageField(upload_to=image_folder)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})

def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name), reversed=True))
        instance.slug = slug
pre_save.connect(pre_save_category_slug, sender=Category)


class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name



class ProductManager(models.Manager):

    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)

class Product(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE,)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE,)
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})

class CartItem(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE,)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return "Cart item for product {0}".format(self.product.title)

class Cart(models.Model):
    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()

    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()

    def change_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.items.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()


ORDER_STATUS_CHOICES = (
    ('Принят в оброботку', 'Принят в оброботку'),
    ('Выполняется', 'Выполняется'),
    ('Оплачен', 'Оплачен')
)


class Order(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    items = models.ManyToManyField(Cart)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    buying_type = models.CharField(max_length=40, choices = (('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')), default='Самовывоз')
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

    def __str__(self):
        return 'Заказ #{0}'.format(str(self.id))

shop/ecomapp/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils import timezone


class OrderForm(forms.Form):
    name = forms.CharField()
    last_name = forms.CharField(required=False)
    phone = forms.CharField()
    buying_type = forms.ChoiceField(widget=forms.Select(), choices=([('self', 'Самовывоз'),('delivery', 'Доставка')]))
    date = forms.DateField(widget=forms.SelectDateWidget(), initial=timezone.now())
    address = forms.CharField(required=False)
    comments = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['phone'].label = 'Контактный номер телефона'
        self.fields['phone'].help_text = 'Пожалуйста, указывайте правильный номер, по которому с Вами можно связаться'
        self.fields['buying_type'].label = 'Способ получения'
        self.fields['address'].label = 'Адрес доставки'
        self.fields['address'].help_text = '*Обязательно указывайте город!'
        self.fields['comments'].label = 'Коментарии к заказу'
        self.fields['date'].label = 'Дата доставки'
        self.fields['date'].help_text = 'Доставка производится на следующий день после оформления заказа. С вами свяжется менеджер.'

shop/ecomapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from ecomapp.forms import OrderForm
from .models import Category, Product, Discount, CartItem, Cart
from decimal import Decimal

# Create your views here.
def index(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    products = Product.objects.all()
    discounts = Discount.objects.all()
    contex = {
        'categories': categories,
        'products': products,
        'discounts': discounts,
    }
    return render(request, 'ecomapp/index.html', contex)

def product_view(request, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    contex = {
        'product' : product,
        'categories': categories,
        'cart': cart
    }
    return render(request, 'ecomapp/product.html', contex)

def category_view(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    categories = Category.objects.all()
    products_of_category = Product.objects.filter(category=category)
    contex = {
        'category' : category,
        'products_of_category':products_of_category,
        'categories': categories
    }
    return render(request, 'ecomapp/category.html', contex)

def cart_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except Exception as e:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    contex = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'ecomapp/cart.html', contex)

def add_to_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def remove_from_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})

def change_item_qty(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart_item = CartItem.objects.get(id=int(item_id))
    cart.change_qty(qty, item_id)
    return JsonResponse({
        'cart_total': cart.items.count(),
        'item_total': cart_item.item_total,
        'cart_total_price': cart.cart_total
    })

def checkout_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'ecomapp/checkout.html', context)


def order_create_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    contex = {
        'form': form
    }
    return render(request, 'ecomapp/order.html', contex)

def make_order_view(request):
        try:
            cart_id = request.session['cart_id']
            cart = Cart.objects.get(id=cart_id)
            request.session['total'] = cart.items.count()
        except:
            cart = Cart()
            cart.save()
            cart_id = cart.id
            request.session['cart_id'] = cart_id
            cart = Cart.objects.get(id=cart_id)
        form = OrderForm(request.POST or None)
        if form.is_valid():
            name = form.cleaned_data['name']
            last_name = form.cleaned_data['last_name']
            phone = form.cleaned_data['phone']
            buying_type = form.form.cleaned_data['buying_type']
            address = form.cleaned_data['address']
            comments = form.cleaned_data['comments']
            new_order = Order()
            new_order.user = request.user
            new_order.save()
            new_order.first_name = name
            new_order.last_name = last_name
            new_order.phone = phone
            new_order.address = address
            new_order.buying_type = buying_type
            new_order.comments = comments
            new_order.total = cart.cart_total
            new_order.save()
            del request.session['cart_id']
            del request.session['total']
            return HttpResponseRedirect(reverse('thank_you'))

shop/ecomapp/templates/ecomapp/cart.html
{% extends 'ecomapp/index.html' %}
{% load static %}
{% block content %}
<br>
{% if cart.items.count > 0 %}
<div class="my-cart">
  <table class="table">
    <tr>
      <td class="text-center">Товар</td>
      <td class="text-center">Количество</td>
      <td class="text-center">Цена</td>
      <td></td>
    </tr>
    {% for item in cart.items.all %}
    <tr class="cart-item-{{ item.product.id }}">
      <td class="text-center">{{ item.product.title }}</td>
      <td class="text-center">
        <form class="" action="" method="GET">
          <input type="number" name="qty" value="{{ item.qty }}" min='1' style="width: 50px;" class="cart-item-qty" data-id="{{ item.id }}">
        </form>
      </td>
      <td class="text-center" id="cart-item-total-{{ item.id }}">{{ item.item_total }} тг</td>
      <td class="text-center"><a href="#" class="remove_from_cart" data-slug='{{ item.product.slug }}' data-id='{{ item.product.id }}'><button type="button" class="btn btn-default" name="button">Удалить</button></a></td>
    </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td class="text-center">Итого</td>
      <td class="text-center" id="cart-total-price"><strong>{{ cart.cart_total }} тг</strong></td>
      <td></td>
    </tr>
  </table>
  <br>
  <a href="{% url 'checkout' %}" class="d-flex justify-content-end"><button type="button" class="btn btn-info" name="button">Предварительный заказ</button></a>
</div>
<h3 class="cart-empty"></h3>
{% else %}
<h3 class="cart-empty text-center">Ваша корзина пуста</h3>
{% endif %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>
  $(document).ready(function(){
    $('.remove_from_cart').on('click', function(e){
      e.preventDefault()
      product_slug = $(this).attr('data-slug')
      item_product_id = $(this).attr('data-id')
      console.log(item_product_id)
      data = {
        product_slug: product_slug
      }
      $.ajax({
        type: "GET",
        url: '{% url "remove_from_cart" %}',
        data: data,
        success: function(data){
          $("#cart_count").html(data.cart_total)
          $('.cart-item-'+item_product_id).css('display', 'none')
          $('#cart-total-price').html('<strong>'+parseFloat(data.cart_total_price).toFixed(2) + ' тг</strong>')
          if(parseInt(data.cart_total) == 0){
            $('.my-cart').css('display','none')
            $('.cart-empty').html('<h3 class="text-center">Ваша корзина пуста</h3>')
          }
        }
      })
    })
  })
  $(document).ready(function(){
    $('.cart-item-qty').on('click', function(){
      qty = $(this).val()
      item_id = $(this).attr('data-id')
      data = {
        qty: qty,
        item_id: item_id
      }
      $.ajax({
        type: "GET",
        url: {% url 'change_item_qty' %},
        data: data,
        success: function(data){
          $('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2) + ' тг')
          $('#cart-total-price').html('<strong>'+parseFloat(data.cart_total_price).toFixed(2) + ' тг</strong>')
        }

      })
    })
  })
</script>

{% endblock content %}

shop/ecomapp/templates/ecomapp/category.html
{% extends 'ecomapp/index.html' %}

{% block content %}

<div class="row">
  {% for product in products_of_category %}
  <div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
      <a href="{{ product.get_absolute_url }}"><img class="card-img-top mt-2" src="{{ product.image.url }}" alt="" style="width:100px; height:200px; margin:0 auto;display: block;"></a>
      <div class="card-body">
        <h4 class="card-title">
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        </h4>
        <h5>{{ product.price }} тг.</h5>
        <p class="card-text">{{ product.title }}</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
      </div>
    </div>
  </div>
  {% endfor %}

</div>

{% endblock content %}

shop/ecomapp/templates/ecomapp/checkout.html
{% extends 'ecomapp/index.html' %}

{% block content %}
  <table class="table">
    <tr>
      <td class="text-center">Товар</td>
      <td class="text-center">Количество</td>
      <td class="text-center">Цена</td>
      <td></td>
    </tr>
    {% for item in cart.items.all %}
    <tr class="cart-item-{{ item.product.id }}">
      <td class="text-center">{{ item.product.title }}</td>
      <td class="text-center">{{ item.qty }}<td>
      <td class="text-center">{{ item.item_total }} тг</td>
      <td></td>
    </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td class="text-center">Итого</td>
      <td class="text-center" id="cart-total-price"><strong>{{ cart.cart_total }} тг</strong></td>
      <td></td>
    </tr>
  </table>
<a href="{% url 'create_order' %}" class="d-flex justify-content-end"><button type="button" class="btn btn-success" name="button">Оформить заказ</button></a>
{% endblock content %}

shop/ecomapp/templates/ecomapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Shop Homepage</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Главная</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge" style="color:grey;" id="cart_count">{{ cart.items.count }}</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="d-flex justify-content-center">
    <ul class="list-group list-group-horizontal-sm">
      <li class="list-group-item list-group-item-primary text-uppercase" style="display: table-cell;">Все категории<a href=""></a></li>
      {% for category in categories %}
        <li class="list-group-item text-uppercase" style="display: table-cell"><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
      {% endfor %}
    </ul>
  </div>
  </div>

  <!-- Page Content -->
  <div class="container mt-5 mb-5">
    {% block content %}
    <div class="row">


      <!-- /.col-lg-3 -->
      <div class="container-fluid d-flex justify-content-center">
        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            {% for product in discounts %}
              {% if forloop.first %}
                <div class="carousel-item active">
                  <a href="{{ product.get_absolute_url }}"><img class="d-block img-fluid" src="{{ product.image.url }}" alt="First slide" style="height:300px"></a>
                </div>
              {% else %}
                <div class="carousel-item">
                  <a href="{{ product.get_absolute_url }}"><img class="d-block img-fluid" src="{{ product.image.url }}" alt="Second slide" style="height:300px"></a>
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="col-lg-12">



        <div class="row">
          {% for product in products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top mt-2" src="{{ product.image.url }}" alt="" style="width:100px; height:200px; margin:0 auto;display: block;"></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                </h4>
                <h5>{{ product.price }} тг.</h5>
                <p class="card-text">{{ product.title }}</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>
          {% endfor %}

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->
    {% endblock content %}
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->


  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


</body>

</html>

shop/ecomapp/templates/ecomapp/order.html
{% extends 'ecomapp/index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<form class="" action="index.html" method="POST">
  <div class="row">
    <div class="col-sm-4">
      {{ form.name|as_crispy_field }}
    </div>
    <div class="col-sm-4">
      {{ form.last_name|as_crispy_field }}
    </div>
    <div class="col-sm-4">
      {{ form.phone|as_crispy_field }}
    </div>
  </div>
  {{ form.buying_type|as_crispy_field }}
  {{ form.address|as_crispy_field }}
  {{ form.date|as_crispy_field }}
  {{ form.comments|as_crispy_field }}
  <input type="submit" name="" value="Оформить заказ" class="btn btn-success">

</form>
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>
  $(document).ready(function(){
    $('#div_id_address').css('display','none')
    $('#id_buying_type').on('click', function(){
      buying_type = $(this).val()
      if(buying_type == 'delivery'){
        $('#div_id_address').css('display','block')
      }else{
        $('#div_id_address').css('display','none')
      }
    })
    $('#id_date_month').css('width','150px')
    $('#id_date_month').css('display','inline')
    $('#id_date_year').css('width','100px')
    $('#id_date_year').css('display','inline')
    $('#id_date_day').css('width','100px')
    $('#id_date_day').css('display','inline')
  })
</script>
{% endblock %}

shop/ecomapp/templates/ecomapp/product.html
{% extends 'ecomapp/index.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-sm-4 mt-5">
      <img src="{{ product.image.url }}" alt="not found" style="width:150px; height:300px;">
    </div>
    <div class="col-sm-8 mt-5">
      <h3 class="text-center">{{ product.title }}</h3>
      <p>{{ product.description }}</p>
      <hr>
      <p>Цена: <strong>{{ product.price }}</strong></p>
      <a href="#" class="add_to_cart" data-slug='{{ product.slug }}'><button class="btn btn-danger" name=button"">Добавить в корзину</button></a>
    </div>
  </div>
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>
  $(document).ready(function(){
    $('.add_to_cart').on('click', function(e){
      e.preventDefault()
      product_slug = $(this).attr('data-slug')
      data = {
        product_slug: product_slug
      }
      $.ajax({
        type: "GET",
        url: '{% url "add_to_cart" %}',
        data: data,
        success: function(data){
          $("#cart_count").html(data.cart_total)
        }
      })
    })
  })

</script>
{% endblock content %}