findface/findface/urls.py
from django.contrib import admin
from django.urls import path, include
from firstapp.views import upload
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

findface/firstapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.upload, name='upload'),
]

findface/firstapp/models.py
from django.db import models
from django.forms import ModelForm
import os


def image_folder(instance, filename):
    filename = filename.split('.')[0]+ '/' +filename
    print(filename)
    return filename


class WorkSheet(models.Model):
    model_pic = models.ImageField(upload_to = image_folder, blank=True)


class UploadWorkSheetForm(ModelForm):
    class Meta:
        model = WorkSheet
        fields = '__all__'

findface/firstapp/forms.py
from django import forms


class ModelForm(forms.Form):
    file = forms.ImageField()

findface/firstapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
import os
from .models import UploadWorkSheetForm
from .findface import FaceControl
from .models import WorkSheet

def upload(request):
    fc = FaceControl()
    if request.method == 'POST':
        form = UploadWorkSheetForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            #worksheet_id = request.session['worksheet_id']
            worksheets = WorkSheet.objects.values('model_pic').last()
            count = fc.faces(worksheets)
            print(count)
            url_name = worksheets['model_pic'].split('/')[0]
            url_type = worksheets['model_pic'].split('/')[1].split('.')[1]
            urls = []
            for i in count:
                url = url_name + '/face-'+str(i)+ '.' +url_type
                urls.append(url)
            print(urls)
            context = {
                'urls':urls
            }
            return render(request, 'firstapp/index.html', {'urls': urls})
    else:
        form = UploadWorkSheetForm()

    return render(request, 'firstapp/index.html', {'form': form})

findface/firstapp/templates/firstapp/hello.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>hello</h1>
  </body>
</html>

findface/firstapp/templates/firstapp/index.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Sticky Footer Navbar Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sticky-footer-navbar/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="sticky-footer-navbar.css" rel="stylesheet">
  </head>
  <body class="d-flex flex-column h-100" data-media-url="{% get_media_prefix %}">
    <header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Fixed navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</header>
{% block body %}
<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container mt-5">
    <div class="row">
      <div class="container mt-5">
        <div class="row">
          <div class="col-5 offset-1">
            <h1>Загрузите фотографию</h1>

            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="img_load">
                  {{ form.as_p }}
                </div>
                <img id="blah" src="{% static 'ava.jpeg' %}" alt="your image" class="img-fluid img-thumbnail" enctype="multipart/form-data"></img>
                <input type="submit" value = "FindFace" class="btn btn-success" id="ff"/>
            </form>




          </div>
          <div class="col-5 offset-1">
            <h1>Информация</h1>
            {% for url in urls %}
            <div class="mt-2 alert alert-info">
              <div class="row">
                <div class="col-3">
                  <b>Лицо:</b><br>
                </div>
                <div class="col-6 offset-1">
                  <img src="{{ MEDIA_URL }}{{ url }}" alt="foto" class="img-fluid img-thumbnail" id="faces">
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
    </div>
  </div>
</main>
{% endblock %}
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script>
  $(document).ready(function(){
    $('#id_model_pic').attr('onchange','readURL(this);')
  })
  function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result)

            };

            reader.readAsDataURL(input.files[0]);
        }
    }
    $(document).ready(function(){
      $('#ff').on('mousedown', function(){
        $('#blah')
          .attr("src", "{{ MEDIA_URL }}{{ 'qwe/rectangle.jpeg' }}")
      })
    })
</script>
</body>
</html>